// This file is automatically generated.
// Please do not change this file!
export const standard: string;
export const formAccent: string;
export const critical: string;
export const primary: string;
export const secondary: string;
export const callToAction: string;
