// This file is automatically generated.
// Please do not change this file!
export const input: string;
export const inputDisabled: string;
export const formAccent: string;
export const formAccentDisabled: string;
export const selection: string;
export const info: string;
export const card: string;
export const critical: string;
export const primary: string;
export const primaryHovered: string;
export const primaryActive: string;
export const secondary: string;
export const secondaryHovered: string;
export const secondaryActive: string;
export const callToAction: string;
export const callToActionHovered: string;
export const callToActionActive: string;
