// This file is automatically generated.
// Please do not change this file!
export const largeText: string;
export const level1Text: string;
export const level2Text: string;
export const level3Text: string;
export const smallText: string;
export const standardText: string;
export const xsmallText: string;
